node_js: node
script:
- npm run build
deploy:
  provider: npm
  email: rob@calculem.us
  skip_cleanup: true
  api_key:
    secure: ceab1KkpvTZHidR/N/6PXHTe/JFCeFY5PDr7JDWEugPCxGmtur1ZYBI8Txl4Oip30Icwu1RhVngOhAYDQsqGufzugUkTzO3h7+oa+qyOXcgmI1kTjWYJVfYaibWV6YJt6a4AScN1LV2DGcwt4pmjdXFO6CfeluD784FKajgCdWU4hXpBaBHWr1IRndFAM7/WY2Hy+QWQ9KL/UsLsnKU8UPiWsw6AmFyFgtp6n5tBoco8UfwMFrZXDCEFFNlPJ0ffCn+kzysmH50dBcGf9huNmILCA1tkaEzgY/wO//35wAg3TRGtM7ls61T8kw0/2WcBVP4mKxA3WObpXhqTTu8dpcW5aNjRH1o26WYg5Qb/7PSPeW+SvjwWyPkc0rzEutZvUBDFCcnNpmk+rmZRPESKCuyEf+dEWOtpkUBalky+l7G9EgKQieNCbQXBuO3hJN9IhfLSRR2P9QPsiDK/991WLOFczTzdcxWqi1M4ATvSqu4XtfXP4XabTxEVieb9hK4EFgttNKuNr+JQQmbDaSjILyXGxAgR/2z/WypBKm6vKVQckVLehgV1xf1N7W0akHSpbXcDGDPn4SlHryAm8lgScpyx8aBNj0BIjMxkdrwV6tQIIoWMrXGzpEJwxYlW1b9T+5EtBmG+BCcYIs4ltdvDcyiiwgId4ugZuY4CVmCI1qQ=
  on:
    repo: retutch/tutch-worker
    branch: master
